'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const app = fs.readFileSync(path.join(__dirname, '..', 'resources', 'js', 'app.js'), 'utf8');
const eml = fs.readFileSync(path.join(__dirname, '..', 'engine', 'lib', 'eml_import.js'), 'utf8');
const backend = fs.readFileSync(path.join(__dirname, '..', 'engine', 'backend.js'), 'utf8');
assert(eml.includes('// LibraMail 0.4.5 — diagnostic EML par étape'));
assert(eml.includes("withImportStage('parse'"));
assert(eml.includes("withImportStageSync('storage'"));
assert(eml.includes("stage: String(error?.emlStage || 'validation')"));
assert(backend.includes('function writeEmlImportLog('));
assert(backend.includes("'eml-import.log'"));
assert(app.includes('// LibraMail 0.4.5 — invalidation forte du cache après mutation'));
assert(app.includes('cacheEpoch !== listViewCacheEpoch'));
assert(app.includes('invalidateListViewCacheAfterMutation();'));
assert(app.includes('await refreshSidebarCounts();'));
assert(app.includes("t('emlImport.firstError'"));
console.log('[LibraMail] Tests diagnostic/rafraîchissement EML 0.4.5 : OK');
